language: python
python:
  - "2.7"
  - "3.4"
  - "3.5-dev"
install:
  - pip install -r test-requirements.txt
script: make travis
after_success: coveralls
notifications:
  email:
    - silpa-discuss@nongnu.org
  irc:
    channels:
      - 'irc.freenode.net#silpa'
    on_success: #silpa
    on_failure: #silpa
    use_notice: true
